version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
        