name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git and Docker
        run: |
          sudo apt-get clean
          sudo apt-get update -y
          sudo apt-get install -y git
          sudo apt-get remove -y containerd
          sudo apt-get install -y docker.io

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone https://github.com/mathzeggio/CompaniesMS.git
            cd /CompaniesMS
            docker-compose pull
            docker-compose up -d
