name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git clone https://github.com/mathzeggio/CompaniesMS.git /COMPANIESMS
          cd /COMPANIESMS
          docker-compose pull
          docker-compose up -d
